/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConseilsRouteImport } from './routes/conseils'
import { Route as CalculateurRouteImport } from './routes/calculateur'
import { Route as AppareilsRouteImport } from './routes/appareils'
import { Route as IndexRouteImport } from './routes/index'

const ConseilsRoute = ConseilsRouteImport.update({
  id: '/conseils',
  path: '/conseils',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculateurRoute = CalculateurRouteImport.update({
  id: '/calculateur',
  path: '/calculateur',
  getParentRoute: () => rootRouteImport,
} as any)
const AppareilsRoute = AppareilsRouteImport.update({
  id: '/appareils',
  path: '/appareils',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appareils': typeof AppareilsRoute
  '/calculateur': typeof CalculateurRoute
  '/conseils': typeof ConseilsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appareils': typeof AppareilsRoute
  '/calculateur': typeof CalculateurRoute
  '/conseils': typeof ConseilsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appareils': typeof AppareilsRoute
  '/calculateur': typeof CalculateurRoute
  '/conseils': typeof ConseilsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/appareils' | '/calculateur' | '/conseils'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/appareils' | '/calculateur' | '/conseils'
  id: '__root__' | '/' | '/appareils' | '/calculateur' | '/conseils'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppareilsRoute: typeof AppareilsRoute
  CalculateurRoute: typeof CalculateurRoute
  ConseilsRoute: typeof ConseilsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/conseils': {
      id: '/conseils'
      path: '/conseils'
      fullPath: '/conseils'
      preLoaderRoute: typeof ConseilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculateur': {
      id: '/calculateur'
      path: '/calculateur'
      fullPath: '/calculateur'
      preLoaderRoute: typeof CalculateurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appareils': {
      id: '/appareils'
      path: '/appareils'
      fullPath: '/appareils'
      preLoaderRoute: typeof AppareilsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppareilsRoute: AppareilsRoute,
  CalculateurRoute: CalculateurRoute,
  ConseilsRoute: ConseilsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
